name: Build on main
on:
#   create:
#     tags:
#       branches:
#        - "main"
  push:
    branches:
     - "main"
       
jobs:
  build-and-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.0
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Build
        working-directory: .
        run: dotnet build
      - name: Test
        run: dotnet test
#       - name: Release
#         run: dotnet publish -c Release
      
